[package]
name = "bwtui"
version = "0.1.0"
authors = ["Christoph Heiss <contact@christoph-heiss.at>"]
edition = "2018"
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/christoph-heiss/bwtui"
description = " terminal-based vault browser for bitwarden"

[dependencies]
aes = "0.3.2"
base64 = "0.11.0"
block-modes = "0.3.3"
chrono = { version = "0.4.10", features = ["serde"] }
clipboard = "0.5.0"
cursive = { version = "0.12.0", features = ["termion-backend"] }
cursive_buffered_backend = "0.3.1"
cursive_table_view = "0.10.0"
directories = "2.0.2"
failure = "0.1.6"
fuzzy-matcher = "0.3.1"
hkdf = "0.8.0"
hmac = "0.7.1"
log = "0.4.8"
pbkdf2 = "0.3.0"
reqwest = "0.9.24"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
sha2 = "0.8.0"
uuid = { version = "0.8.1", features = ["v4", "serde"] }
unicase = "2.6.0"
