name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build, test, doc, clippy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly

    steps:
      - name: Install required system libraries
        run: |
          sudo apt-get update \
          && sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev

      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
          override: true

      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Generate rustdoc
        uses: actions-rs/cargo@v1
        with:
          command: doc

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
